plugins {
    id 'application'
    id("io.freefair.lombok") version "8.12.1"
}

group 'com.css'
version '1.0'

apply plugin: "java"

repositories {
    mavenCentral()
}

dependencies {
    // https://picocli.info/
    implementation 'info.picocli:picocli:4.7.0'
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.4.2'
    // https://github.com/simple-http/simple-http
    implementation 'com.simple-http:simple-http:1.4'
    implementation 'ch.qos.logback:logback-classic:1.5.16'
    implementation 'org.hsqldb:hsqldb:2.7.1'
}

ext {
    javaMainClass = "com.css.challenge.Main"
}

application {
    mainClass.set(javaMainClass)
}
